### ISSUE TITLE
[1.11.2/3.3.1-a27] Compressed Furnace Issues

### ISSUE THREAD

**Issue by Malkierian** [fabbe50/Compressed-Blocks-2.0#13]
So, I loved discovering the Compressed Furnace.  The speed increase was awesome.  However, I had three issues crop up.  After placing it, I could open up the GUI no problem, but shift-clicking wasn't working, so I had to manually click-place the coal and sand I wanted to smelt.  After I got the coal in there and it started smelting, it kicked the remainder of both stacks out of its inventory, the texture reverted to the vanilla furnace's, and I couldn't access the GUI anymore.  When I then went to break it and place it again, it only dropped a regular furnace.

However, if I have the Compressed Furnace attached to an automatic feeder setup with hoppers, it's able to still pull in the fuel and smelting material as if it was still a Compressed Furnace, and not the vanilla furnace it appears to be.

**Comment by fabbe50** [comment]
I'm aware of the issue, the automation, however, I haven't even thought of. I'll look into it!

**Comment by fabbe50** [comment]
Fixed in 3.3.1-a29
